
name: using artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and generate artifacts
      run: |
        # Your build commands here
        echo "This is a build output" > artifact.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifacts
        path: artifact.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: my-artifacts

    - name: Deploy using artifacts
      run: |
        # Your deployment commands here
        cat my-artifacts/artifact.txt
