name: Capture Output Example

on:
  workflow_dispatch:

jobs:
  capture_output:
    runs-on: ubuntu-latest
    
    
    # outputs:
    #   step_output: ${{ steps.set_output.outputs.output }}

    steps:
      - name: Set Output
        id: set_output
        run: echo "Hello, this is the captured output"
        shell: bash
        env:
          OUTPUT_VAR: ${{ steps.set_output.outputs.output }}

  use_output:
    needs: capture_output
    runs-on: ubuntu-latest

    steps:
      - name: Use Captured Output
        run: |
          echo "The captured output is: $OUTPUT_VAR"
