name: Share Output Between Steps

on:
  workflow_dispatch:

jobs:
  share_output_job:
    runs-on: ubuntu-latest

    outputs:
      env_output: ${{ steps.set_env_output.outputs.env_output }}
      output_var: ${{ steps.set_output_var.outputs.output_var }}

    steps:
      - name: Set Output as Environment Variable
        id: set_env_output
        run: |
          echo "This is the output" >> $GITHUB_ENV
          echo "env_output=${{ env.OUTPUT_ENV }}" >> $GITHUB_ENV
        env:
          OUTPUT_ENV: "This is the output"

      - name: Set Output as Output Variable
        id: set_output_var
        run: |
          echo "::set-output name=output_var::This is the output"

      - name: Use Output in Another Step
        run: |
          echo "Output from environment variable: $OUTPUT_ENV"
          echo "Output from output variable: ${{ needs.share_output_job.outputs.output_var }}"
        env:
          OUTPUT_ENV: ${{ needs.share_output_job.outputs.env_output }}
